---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: "packer-opnsense"
    server_type: cx11
    image: debian-11
    networks:
      molecule-hetznercloud-network-1:
        ip_range: 10.10.0.0/16
        subnet:
          ip: 10.10.10.1/24
          type: cloud
          network_zone: eu-central
      molecule-hetznercloud-network-2:
        ip_range: 10.20.0.0/16
        subnet:
          ip: 10.20.10.1/24
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "/etc/ansible/roles/${playbook_dir}/roles"
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
lint: |
  set -e
  yamllint .
  ansible-lint .
