# this creates the changelog in the description for the Vagrant box
pri_packer_setup_changelog:
- version: '0.2.0'
  date: 2017-12-01
  changes:
  - Create a custom Vagrantfile template for the final image that includes the username and other required settings
  - Moved sysprep process before the image is created
  - Added `slmgr.vbs /rearm` to run just after Vagrant starts the image to get the full evaluation period possible
  - Removed SSL certificates that were created during the packer build process
  - Installed [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) v0.0.23.0 on all images eacept Server 2008
  - Added .travis-ci file to run [ansible-lint](https://github.com/willthames/ansible-lint) on the Ansible files for some testing sanity
  - Decided to install the VirtualBox guest additions tools as part fo the build process
  - Added vim to the list of chocolatey packages to help with Core OS installs or connecting via SSH
  host_specific_changes:
    1709:
    - Added support for Windows Server 1709
    - This won't be available in Vagrant Cloud as it is not avaible as a public evaluation ISO
    2016:
    - Will not remove Features on Demand until [this](https://social.msdn.microsoft.com/Forums/en-US/2ad1c1d9-09ba-407e-ba03-951c6f2baa34/features-on-demand-server-2016-source-not-found?forum=ws2016) is resolved
    2008r2:
    - Enabled TLSv1.2 cipher support for both the client and server components
    2008-x64:
    - Disabled screensaver to stop auto logoff by default
    - Ensure TLSv1.2 cipher support KB is installed but not enabled due to bug in the server implementation
    2008-x86:
    - Disabled screensaver to stop auto logoff by default
    - Ensure TLSv1.2 cipher support KB is installed but not enabled due to bug in the server implementation
- version: '0.&0.1'
  date: 2020-1-20
  changes:
  - First images built by this process

pri_packer_setup_builders_info:
  common:
    iso_url: '{{ pri_packer_setup_config.iso_url }}'
    iso_checksum: '{{ pri_packer_setup_config.iso_checksum }}'
    iso_checksum_type: md5
    communicator: winrm
    disk_size: '{{ opt_packer_setup_disk_size_mib | default(40960) }}'
    winrm_username: '{{ opt_packer_setup_username }}'
    winrm_password: '{{ opt_packer_setup_password }}'
    winrm_port: '5985'
    winrm_timeout: '240m'
    shutdown_command: schtasks.exe /Run /TN "packer-shutdown"
    shutdown_timeout: 15m
  virtualbox:
    type: virtualbox-iso
    guest_additions_mode: 'attach'
    vboxmanage:
    -
      - modifyvm
      # need to double escape the Jinja2 {{.Name}} value so Ansible doesn't see it as a variable
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --memory
      - "2048"
    -
      - modifyvm
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --vram
      - "48"
    -
      - modifyvm
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --cpus
      - "2"
    -
      - modifyvm
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --natpf1
      - winrm,tcp,127.0.0.1,{{ pri_packer_setup_config.vb_forwarded_port }},,5985
    -
      - storagectl
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --name
      - Sata Controller
      - --add
      - sata
      - --controller
      - IntelAHCI
    -
      - storageattach
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --storagectl
      - Sata Controller
      - --port
      - "1"
      - --device
      - "0"
      - --type
      - dvddrive
      - --medium
      - '{{ man_packer_setup_host_type }}/secondary.iso'
    -
      - storageattach
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --storagectl
      - Sata Controller
      - --port
      - "2"
      - --device
      - "0"
      - --type
      - dvddrive
      - --medium
      - '{{ man_packer_setup_host_type }}/virtio.iso'
    vboxmanage_post:
    -
      - storagectl
      - "{% raw %}{{ '{{' }}.Name{{ '}}' }}{% endraw %}"
      - --name
      - Sata Controller
      - --remove
    guest_os_type: '{{ pri_packer_setup_config.vb_guest_os_type }}'
    headless: '{{ opt_packer_setup_headless }}'
  hyperv:
    type: hyperv-iso
    boot_command:
    - a<enter><wait>a<enter><wait>a<enter><wait>a<enter>
    boot_wait: 2s
    cpus: 2
    generation: '{{ pri_packer_setup_config.hv_generation|int }}'
    memory: 2048
    secondary_iso_images: 
    - '{{ man_packer_setup_host_type }}/secondary.iso'
    switch_name: '{{ opt_packer_setup_hyperv_switch|default("packer-windoze") }}'
    headless: '{{ opt_packer_setup_headless }}'
  qemu:
    type: qemu
    cpus: 2
    disk_interface: virtio
    disk_compression: true
    headless: '{{ opt_packer_setup_headless }}'
    memory: 2048
    net_device: virtio-net
    ssh_host_port_min: 5985
    ssh_host_port_max: 5985
    qemuargs:
    -
      - -netdev
      - user,id=user.0,hostfwd=tcp::5985-:5985
    -
      - -drive
      - file={{ man_packer_setup_host_type }}/secondary.iso,index=0,media=cdrom
    -
      - -drive
      - file={{ man_packer_setup_host_type }}/virtio.iso,index=1,media=cdrom
    # This entry probably needs to be removed in a future release, I think it's a bug where the drive is removed if
    # qemuargs is used and is fixed in an unreleased version right now.
    -
      - -drive
      - file=output-qemu/packer-qemu,if=virtio,cache=writeback,discard=ignore,format=qcow2

pri_packer_setup_provisioners_info:
  common: []
  virtualbox:
  - type: shell-local
    command: ansible-playbook main.yml -i {{ man_packer_setup_host_type }}/hosts.ini -vv
  hyperv:
  # get the IP address of the host and store it as a file
  - type: powershell
    inline: 
    - (Get-CimInstance -ClassName Win32_NetworkAdapterConfiguration -Filter "IPEnabled=True")[0].IPAddress[0] | Set-Content -Path C:\Windows\TEMP\ip.txt
  # get the file that contains the IP address locally
  - type: file
    source: C:\Windows\TEMP\ip.txt
    destination: '{{ man_packer_setup_host_type }}/hyper-v-ip.txt'
    direction: download
  # replace the IP in the Ansible inventory with the real IP
  - type: shell-local
    script: '{{ man_packer_setup_host_type }}\configure-hyperv-network.ps1'
    execute_command:
    - powershell.exe
    - -ExecutionPolicy
    - ByPass
    - -File
    - '{% raw %}{{ "{{" }}.Script{{ "}}" }}{% endraw %}'
  - type: shell-local
    # Packer creates a tmp script for command which won't work for bash.exe -ic, we set the actual command we want to
    # use in execute_command and have a dummy value here
    command: dummy
    execute_command:
    - bash.exe
    - -ic
    - ansible-playbook main.yml -i {{ man_packer_setup_host_type }}/hosts.ini -vv
  qemu:
  - type: shell-local
    command: ansible-playbook main.yml -i {{ man_packer_setup_host_type }}/hosts.ini -vv

pri_packer_setup_post_processors_info:
  common:
    type: vagrant
    output: "{{ man_packer_setup_host_type }}/{{ opt_packer_setup_builder }}.box"
    vagrantfile_template: "{{ man_packer_setup_host_type }}/vagrantfile.template"
  virtualbox: {}
  hyperv: {}
  qemu: {}

pri_packer_setup_json:
  builders:
  - '{{ pri_packer_setup_builders }}'
  provisioners: '{{ pri_packer_setup_provisioners }}'
  post-processors:
  - '{{ pri_packer_setup_post_processors }}'

# host settings like url's, checksums, vbox types, etc
#   iso_url: The URL of the evaluation ISO
#   iso_checksum: The md5 checksum of the evaluation ISO

#   VirtualBox specifics for the host
#   vb_guest_os_type: The VirtualBox guest os type used when builing the VM, run 'VBoxManage list ostypes' to get a valid list
#   vb_forwarded_port: The port to set on 127.0.0.1 that will forward to port 5986 on the Windows host, this should be unique

#   Hyper-V specific for the host
#   hv_generation: The Hyper-V generation to use for the OS, either 1 or 2

#   Host Information generic to the Ansible setup
#   iso_wim_label: The WIM Name on the install ISO of the edition to install
#   architecture: The architecture of the build (x86 or amd64) for the answer file
#   answer_longhorn: Whether the host type will use the older Server 2008 answer file
#   product_key: The KMS product key required in setup, only used in Server 2008 answer file
#   box_tag: This is the box tag that I use, this can be overriden with opt_packer_setup_box_tag
#   driver_host_string: The host string name used for the Virtio drivers
#   bootstrap_files: A list of dictionaries that contains files to download for use in the bootstrapping process, this also modifies the bootstrapping script
pri_packer_setup_host_config:
  # host pattern <osname-[architecture]-[option]> where architecture and option
  # are optional and will default to x64 and minimal by default
  '2008-x86':
    box_tag: jborean93/WindowsServer2008-x86

    iso_url: https://download.microsoft.com/download/D/D/B/DDB17DC1-A879-44DD-BD11-C0991D292AD7/6001.18000.080118-1840_x86fre_Server_en-us-KRMSFRE_EN_DVD.iso
    iso_checksum: 89fbc4c7baafc0b0c05f0fa32c192a17
    vb_guest_os_type: Windows2008
    vb_forwarded_port: 55981
    hv_generation:

    iso_wim_label: Windows Longhorn SERVERSTANDARD
    architecture: x86
    answer_longhorn: yes
    product_key: TM24T-X9RMF-VWXK6-X8JC9-BFGM2
    driver_host_string: 2k8
    bootstrap_files:
    - name: Server 2008 SP2
      url: https://download.microsoft.com/download/E/7/7/E77CBA41-0B6B-4398-BBBF-EE121EEC0535/Windows6.0-KB948465-X86.exe
    - type: update
      name: KB968930  # PowerShell v2.0
      product: Windows Server 2008
    - type: update
      name: KB971512  # Pre-req 1 for IE9
      product: Windows Server 2008
    - type: update
      name: KB2117917  # Pre-req 2 for IE9
      product: Windows Server 2008
    - name: Internet Explorer 9
      url: http://download.windowsupdate.com/msdownload/update/software/updt/2011/03/wu-ie9-windowsvista-x86_a2b66ff9e9affda9675dd85ba2b637a882979a25.exe
    - name: .NET v4.5
      url: http://download.microsoft.com/download/B/A/4/BA4A7E71-2906-4B2D-A0E1-80CF16844F5F/dotNetFx45_Full_x86_x64.exe
      arguments: /q /norestart
    - name: PowerShell v3
      url: https://download.microsoft.com/download/E/7/6/E76850B8-DA6E-4FF5-8CCE-A24FC513FD16/Windows6.0-KB2506146-x86.msu
    - name: WMFv3 Memory Hotfix
      action: install-zip
      zip_file_pattern: '*KB2842230*.msu'
      file: KB2842230-wmfv3.zip
      url: https://s3.amazonaws.com/ansible-ci-files/hotfixes/KB2842230/464091_intl_i386_zip.exe
    - type: update
      name: KB4493730  # April 9 2019 SSU Update (required for rollup updates)
      product: Windows Server 2008
    - type: update
      name: KB4474419  # SHA-2 update compat
      product: Windows Server 2008
    - type: update
      name: Servicing Stack Update for Windows Server 2008
      product: Windows Server 2008
    - type: update
      name: Security Monthly Quality Rollup for Windows Server 2008
      product: Windows Server 2008