# this creates the changelog in the description for the Vagrant box
pri_packer_setup_changelog:
- version: '0.&0.1'
  date: 2022-04-29
  changes:
  - First images built by this process

pri_packer_setup_builders_info:
  common:
    iso_url: '{{ pri_packer_setup_config.iso_url }}'
    iso_checksum: '{{ pri_packer_setup_config.iso_checksum }}'
    iso_checksum_type: md5
  hetzner:
    type: hetzner
    guest_additions_mode: 'attach'
    guest_os_type: '{{ pri_packer_setup_config.vb_guest_os_type }}'
    headless: '{{ opt_packer_setup_headless }}'

pri_packer_setup_provisioners_info:
  common: []
  hetzner: []

pri_packer_setup_post_processors_info:
  common: {}
  hetzner: {}

pri_packer_setup_json:
  builders:
  - '{{ pri_packer_setup_builders }}'
  provisioners: '{{ pri_packer_setup_provisioners }}'
  post-processors:
  - '{{ pri_packer_setup_post_processors }}'

pri_packer_setup_host_config:
  # host pattern <osname-[architecture]-[option]> where architecture and option
  # are optional and will default to x64 and minimal by default
  'debian-11':
    box_tag: breizland/debian11
    iso_url: https://debian.obspm.fr/debian-cd/11.3.0/amd64/iso-dvd/debian-11.3.0-amd64-DVD-1.iso
    iso_checksum: 89fbc4c7baafc0b0c05f0fa32c192a17fab0b6d2ea4fa4fb14100225fcb2988b94a8e391f273b4bfaed6314dff124a42
    vb_guest_os_type: debian
    vb_forwarded_port: 55981
    hv_generation: